name: Prowler for AWS Organization to Security Hub
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: 'Select Environment name'
        options:
          - 
          - production
          - development
          - staging
          

env:
  awsRegion: us-east-1
  awsIamRoleSessionDuration: 3600

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  run-prowler:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}  
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.10'
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWSROLETOASSUME }}  
          role-session-name: OIDCSession
          aws-region: ${{ env.awsRegion }}
          role-duration-seconds: ${{ env.awsIamRoleSessionDuration }}
        
      - name: Verify AWS Credentials
        run: aws sts get-caller-identity
        
      - name: Install Prowler
        run: |
          pip install prowler
          prowler -v
        
      - name: Run Prowler and send findings to Security Hub
        run: |
          prowler aws -z  --services s3 ec2 --security-hub
        continue-on-error: true
        
      - name: Debug Environment Variables
        run: env

      - name: Completion Message
        run: |
          echo "Prowler run completed in environment: ${{ github.event.inputs.environment123 }}"
