name: Prowler for AWS Organization to Security Hub
on:
  workflow_dispatch:
    inputs:
    environment123:
    required: true
    type: choice
    description: 'Select Environment name'
    options:
          - 
          - production
          - staging
          - development

env:
  awsRegion: us-east-1
  awsIamRoleSessionDuration: 3600

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  run-prowler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.10'
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWSROLETOASSUME }}  
          role-session-name: OIDCSession
          aws-region: ${{ env.awsRegion }}
          role-duration-seconds: ${{ env.awsIamRoleSessionDuration }}
        
      - name: Install Prowler
        run: |
          pip install prowler
          prowler -v
        
      - name: Run Prowler and send findings to Security Hub
        run: |
          prowler aws --services s3 ec2 --security-hub
        continue-on-error: true
        
      - name: Completion Message
        run: |
          echo "Prowler run completed in environment: ${{ github.event.inputs.environment }}"
